---
title: "Research"
---

## Research interests
My work focuses on applying advanced spatiotemporal methods to model and map the risk of Neglected Tropical Diseases (NTDs), including snakebite envenoming (SBE), soil-transmitted helminths (STH), and lyphatic filariais (LF), influencing policy and control strategies in low- and middle-income countries.

* **Mapping Snakebite Risk:** Developed high-resolution spatiotemporal models to predict envenoming hotspots.
* **STH Control Strategies:** Evaluated the impact of mass drug administration on soil-transmitted helminth prevalence.
* **LF Elimination:** Designing elimination surveys to support the global program to eliminate lymphatic filariasis.


## Doctoral Research 
*Thesis: “Spatiotemporal Methods and Applications in Neglected Tropical Diseases”*  
University of Kelaniya, Sri Lanka & Lancaster University, United Kingdom  
Commonwealth Doctoral Scholarship (split-site) recipient (2017)

Publications in Peer-reviewed Indexed Journals arising from the thesis  

* Ediriweera DS, et al (2016). PLoS NTD 10(7): e000481. 
* Ediriweera DS, et al (2017). PLoS NTD 11(11): e0006073.
* Ediriweera DS, et al (2018). International Journal of Epidemiology 47(6).
* Ediriweera DS, et al (2019). PLoS ONE 14(10): e0223021.
* Ediriweera DS, et al. (2019). The Lancet Global Health 7(9).
* Ediriweera DS, et al. (2021). PLoS NTD 15(6): e0009447.

Awards arising from the thesis  

* President’s Awards for Scientific Publication (2016)
* President’s Awards for Scientific Publication (2017)
* President’s Awards for Scientific Publication (2018)
* President’s Awards for Scientific Publication (2019)
* Wilson Peiris Prize, Sri Lanka Medical Association (2016)
* Third place poster prize, Royal Statistical Society International Conference (2018)
* Taylor & Francis Commonwealth Scholar Best Journal Article Prize 2020 - highly commended for publication (one of the three finalists)


## Complete Bibliography & Citation Metrics
A live-updated repository of my peer-reviewed work, citation trajectories, and co-author networks can be accessed via my My [Google Scholar Profile](https://scholar.google.com/citations?user=ZDZy6sEAAAAJ&hl=en). A chronological list of my first author and co-author publications are also detailed below.


## First author Publications
* **Ediriweera DS**, Kasturiratne A, Pathmeswaran A, Stienstra Y, Martín G, Iwamura T, Murray KA, de Silva HJ, Diggle PJ, Lalloo DG. Estimates of global burden of snakebite: a literature review and geostatistical modelling study. *PLoS Medicine*. In press.
* **Ediriweera DS**, Hakizimana D, Diggle PJ, Schurer JM. Community-based snakebite risk mapping for resource prioritisation in Eastern Province, Rwanda. *Transactions of The Royal Society of Tropical Medicine and Hygiene*. 2025 Jan 3:trae069.
* **Ediriweera DS**, de Silva T, Kasturiratne A, de Silva HJ, Diggle P. Geographically regulated designs of incidence surveys can match the precision of classical survey designs whilst requiring smaller sample sizes: the case of snakebite envenoming in Sri Lanka. *BMJ Global Health*. 2022 Oct 1;7(10):e009500.
* **Ediriweera DS**, Kasthuriratne A, Pathmeswaran A, Gunawardene NK, Jayamanne SF, Murray K, Iwamura T, Isbister G, Dawson A, Lalloo DG, de Silva HJ. Evaluating spatiotemporal dynamics of snakebite in Sri Lanka: Monthly incidence mapping from a national representative survey sample. *PLoS neglected tropical diseases*. 2021 Jun 1;15(6):e0009447.
* **Ediriweera DS**, De Silva NR, Malavige GN, De Silva HJ. An epidemiological model to aid decision-making for COVID-19 control in Sri Lanka. *PLoS ONE*. 2020 Aug 27;15(8):e0238340.
* **Ediriweera DS**, Gunawardena S, Gunawardena NK, Iddawela D, Kannathasan S, Murugananthan A, Yahathugoda C, Pathmeswaran A, Diggle PJ, de Silva N. Reassessment of the prevalence of soil-transmitted helminth infections in Sri Lanka to enable a more focused control programme: a cross-sectional national school survey with spatial modelling. *The Lancet Global Health*. 2019 Sep 1;7(9):e1237-46.
* **Ediriweera DS**, Kasthuriratne A, Pathmeswaran A, Gunawardene NK, Jayamanne SF, Murray K, Iwamura T, Lalloo DG, de Silva HJ, Diggle PJ. Adjusting for spatial variation when assessing individual-level risk: A case-study in the epidemiology of snake-bite in Sri Lanka. *PloS one*. 2019 Oct 3;14(10):e0223021.
* **Ediriweera DS**, Diggle PJ, Kasturiratne A, Pathmeswaran A, Gunawardena NK, Jayamanne SF, Isbister GK, Dawson A, Lalloo DG, de Silva HJ. Evaluating temporal patterns of snakebite in Sri Lanka: the potential for higher snakebite burdens with climate change. *International journal of epidemiology*. 2018 Dec 1;47(6):2049-58.
* **Ediriweera DS**, Karunapema P, Pathmeswaran A, Arnold M. Increase in premature mortality due to non-communicable diseases in Sri Lanka during the first decade of the twenty-first century. *BMC Public Health*. 2018 Dec;18(1):1-6
* **Ediriweera DS**, Dilina N, Saparamadu V, Fernando I, Kurukulasuriya B, Fernando D. Aspirin is associated with low oral pH levels and antacid helps to increase oral pH. BMC research notes. 2018 Dec;11(1):1-5.
* **Ediriweera DS**, Kasturiratne A, Pathmeswaran A, Gunawardena NK, Jayamanne SF, Lalloo DG, de Silva HJ. Health seeking behavior following snakebites in Sri Lanka: Results of an island wide community based survey. *PLoS neglected tropical diseases*. 2017 Nov 6;11(11):e0006073.
* **Ediriweera DS**, Kasturiratne A, Pathmeswaran A, Gunawardena NK, Wijayawickrama BA, Jayamanne SF, Isbister GK, Dawson A, Giorgi E, Diggle PJ, Lalloo DG, de Silva HJ. Mapping the risk of snakebite in Sri Lanka-a national survey with geospatial analysis. *PLoS neglected tropical diseases*. 2016 Jul 8;10(7):e0004813.
* **Ediriweera DS**, Dilina N, Perera U, Flores F, Samita S. Risk of low birth weight on adulthood hypertension-evidence from a tertiary care hospital in a South Asian country, Sri Lanka: a retrospective cohort study. *BMC Public Health*. 2017 Dec;17(1):1-6
* **Ediriweera DS**, Kumarage S, Deen KI. Comparison of hazard of death following surgery for colon versus rectal cancer. Ceylon Medical Journal. *Ceylon Medical Journal*. 2016; 61(2), pp.52–55.

## Full list of publications
* **Ediriweera DS**, Kasturiratne A, Pathmeswaran A, Stienstra Y, Martín G, Iwamura T, Murray KA, de Silva HJ, Diggle PJ, Lalloo DG. Estimates of global burden of snakebite: a literature review and geostatistical modelling study. *PLoS Medicine*. In press.
* De Silva ST, **Ediriweera D**, Niriella MA, Kasturiratne A, Pathmeswaran A, Kato N, Wickramasinghe R, de Silva HJ. Chronic Kidney Disease in Urban, Adult Sri Lankans: A Cohort Follow-up Study. *International Journal of Nephrology*. 2026 May 14; 2026(1).
* De Silva S, **Ediriweera D**, Ekanayake N, Solangaarachchi T, Perera K, Wickremasinghe A, Liyanage R. Patterns of COVID-19 mortality during the second and third waves in Sri Lanka: a cross-sectional study from a tertiary care center. *BMC Infectious Diseases*. 2026 Apr 30.
* Karaunarathne J, Warnakulasuriya S, Perera C, Premathilaka H, Rajapaksha M, Perera S, **Ediriweera D**, Premawardhena A. Comparative Study of Ferritin Levels between Two Generic Formulations of Deferasirox in Sri Lankan Patients with Beta-Thalassemia Major. *Hemoglobin*. 2026 Apr 6:1-8.
* Padeniya P, **Ediriweera D**, Niriella M, De Silva A, Kottahachchi D, Premawardhena A. The splenectomy paradox in thalassemia: reduced transfusion requirements vs. accelerated hepatic fibrogenesis. *Mediterranean Journal of Hematology and Infectious Diseases*. 2026 Mar 1;18(1):e2026023.
* Rambukwella G, **Ediriweera DS**, Isuru A. Prevalence of anxiety, depression and stress symptoms among doctors in COVID-19 treatment units: a cross-sectional study in Anuradhapura, Sri Lanka. *BMJ Open*. 2026 Mar;16(3):e100281.
* Deen R, Chandrasinghe P, **Ediriweera D**, Godahewa S, Gunathilake B, Mahendra G, Hewavisenthi J, Kumarage S. Colorectal cancer survivorship in a cohort of Sri Lankan patients; the time to widen focus from the care of acute patients to long-term survivors. *Sri Lanka Journal of Surgery*. 2026 Jan 5;43(3).
* **Ediriweera DS**, Hakizimana D, Diggle PJ, Schurer JM. Community-based snakebite risk mapping for resource prioritisation in Eastern Province, Rwanda. *Transactions of The Royal Society of Tropical Medicine and Hygiene*. 2025 Mar;119(3):310-6.
* De Silva ST, **Ediriweera DS**, Niriella MA, Beddage T, Kasturiratne A, Pathmeswaran A, Kato N, Wickramasinghe R, de Silva HJ. Incidence and predictors of diabetes mellitus: A 7-year community cohort follow-up of urban, adult Sri Lankans. *International Journal of Diabetes in Developing Countries*. 2025 Jun;45(2):373-9.
* Hettige S, Solangaarahchi I, **Ediriweera DS**. Applying UTAUT to understand medical students’ Wi-Fi adoption for learning in Sri Lankan hostel settings. *Discover Education*. 2025 Oct 14;4(1):416.
* Rathnayake DW, Sooriyaarachchi P, Niriella MA, **Ediriweera D**, Perera J. Herbal treatments for non-alcoholic fatty liver disease: A systematic review and meta-analysis of randomized controlled trials. *Advances in Integrative Medicine*. 2025 Sep 1;12(3):100410.
* Chandrasena N, **Ediriweera D**, Jayakody D, Gunathilaka N, Premaratna R. An Overview of Dengue Knowledge, Attitudes, and Practices (KAPs) Among the General Public in Sri Lanka: A Review and Meta-Analysis of Questionnaire-Based Surveys from 2000–2023. *Tropical Medicine and Infectious Disease*. 2025 Jul 6;10(7):189.
* Niriella MA, Premaratna P, Senanayake M, Kodisinghe S, Dassanayake U, Dassanayake A, **Ediriweera DS**, de Silva HJ. The reliability of freely accessible, baseline, general-purpose large language model generated patient information for frequently asked questions on liver disease: a preliminary cross-sectional study. *Expert Review of Gastroenterology & Hepatology*. 2025 Apr 3;19(4):437-42.
* Niriella MA, Martinus CK, Withanage MY, Darshika S, Illangasinghe M, Perera HR, **Ediriweera DS**, de Silva HJ. Clinical epidemiology of inflammatory bowel disease among adults in the South Asian Region: A systematic review and meta-analysis. *Heliyon*. 2025 Jan 11.
* De Silva AP, Prabagar K, Wickramasinghage AS, Wanniarachchi AA, **Ediriweera DS**, Niriella MA, De Silva HJ, De Silva A, Sewwandi A, Wanniarachchi A. The Significance of the Presence of Gilbert's Syndrome in Patients With Metabolic Dysfunction-Associated Steatotic Liver Disease (MASLD): A Retrospective Cohort Study. *Cureus*. 2025 May 30;17(5).
* De Silva ST, **Ediriweera DS**, Wimalasena W, Kariyawasam M, Kosinna G, Bogoda G, Senaratne S, Rathnayake K, Weerarathna I, Premaratna R, Gunasena P. Evaluation of BBIBP-CorV Sinopharm COVID-19 vaccine effectiveness in Sri Lanka: a test-negative case control study. *BMJ Open*. 2024 Nov 1;14(11):e090341.
* Gunaratna IE, Chandrasena NT, Vallipuranathan M, Premaratna R, **Ediriweera D**, de Silva NR. The impact of the National Programme to Eliminate Lymphatic Filariasis on filariasis morbidity in Sri Lanka: Comparison of current status with retrospective data following the elimination of lymphatic filariasis as a public health problem. *PLOS Neglected Tropical Diseases*. 2024 Aug 14;18(8):e0012343.
* Amiyangoda G, Antonypillai CN, Gunatilake SS, Weerathunge TT, **Ediriweera D**, Kosgallana SG, Jayawardana RD, Thissera HA, Emalka WJ, Daraniyagala HU. Rapid supervised levothyroxine absorption test in refractory hypothyroidism: suggestion for assessing absorption using two blood samples in low-resource settings. *Endocrine Connections*. 2024 Oct 1;13(10).
* Klepac P, Hsieh JL, Ducker CL, Assoum M, Booth M, Byrne I, Dodson S, Martin DL, Turner CM, van Daalen KR, Abela B, Akamboe J, Alves F, Brooker SJ, Ciceri-Reynolds K, Cole J, Desjardins A, Drakeley C, **Ediriweera D**, et al. Climate change, malaria and neglected tropical diseases: a scoping review. *Transactions of The Royal Society of Tropical Medicine and Hygiene*. 2024 Sep;118(9):561-79.
* Martín G, Erinjery JJ, **Ediriweera D**, Goldstein E, Somaweera R, de Silva HJ, Lalloo DG, Iwamura T, Murray KA. Effects of global change on snakebite envenoming incidence up to 2050: a modelling assessment. *The Lancet Planetary Health*. 2024 Aug 1;8(8):e533-44.
* Mettananda C, de Silva S, **Ediriweera D**, Hettiarachchi M, Wanigatunge C, Wanigasuriya K. Guide to clinical audits. *Journal of the Ceylon College of Physicians*. 2024 Dec 20;55(2).
* Sanchayan S, Mahendra BA, **Ediriweera D**, Hettiarachchi G, Liyanage SK, Bopagoda M, Chandratilake M, Hewavisenthi SD. Postgraduate trainees’ perception of the impact of a web-based histopathology reporting system on their training: a single-centre experience. *Journal of Diagnostic Pathology*. 2024 Dec 31;19(2).
* Senandheera VV, Muthukumarana CK, **Ediriweera DS**, Rupasinghe TP. Impact of microlearning on academic performance of students in higher education: A systematic review and meta-analysis. *Journal of Multidisciplinary & Translational Research*. 2024 Aug 29;9(1).
* Senadheera VV, Rupasinghe TP, **Ediriweera DS**. ‘Connective Alignment’ as the Educational Approach for Higher Education in the Digital Age. *Journal of Learning for Development*. 2024; 11(1), 172–180.
* Senadheera VV, **Ediriweera DS**, Rupasinghe TP. Instructional design models for digital learning in higher education — A scoping review. *Journal of Learning for Development*. 2024; 11(1), 15-26.
* Rambukwella GU, **Ediriweera D** and Isuru A. Prevalence and associated factors of burnout among doctors working in hospitals with COVID-19 treatment units in Anuradhapura district, Sri Lanka during the COVID-19 pandemic: A descriptive cross-sectional study. *Sri Lanka Journal of Psychiatry*. 2023 Apr; 14(2): 23-30.
* Padeniya P, **Ediriweera D**, De Silva AP, Niriella M, Premawardhena A. The association between steatosis and liver damage in transfusion‐dependent beta thalassaemia patients. *British Journal of Haematology*. 2023 Feb;200(4):517-523.
* Deen R, **Ediriweera DS**, Thillakaratne S, Hewavissenthi J, Kumarage SK, Chandrasinghe PC. Neoadjuvant Chemoradiation for Rectal Cancer Achieves Satisfactory Tumour Regression and Local Recurrence–Result of a Dedicated Multi-disciplinary Approach from a South Asian Centre. *BMC Cancer*. 2023 Dec;23(1):1-8.
* Niriella MA, **Ediriweera DS**, Withanage MY, Darshika S, De Silva ST, de Silva HJ. Prevalence and associated factors for non-alcoholic fatty liver disease among adults in the South Asian Region: a meta-analysis. *The Lancet Regional Health-Southeast Asia*. 2023 Aug 1;15.
* Chandrasena NT, Gunaratna IE, **Ediriweera D**, de Silva NR. Lymphatic filariases and soil-transmitted helminthiases in Sri Lanka: the challenge of eliminating residual pockets of transmission. *Philosophical Transactions of the Royal Society B*. 2023 Oct 9;378(1887):20220280.
* Goldstein E, Erinjery JJ, Martin G, Kasturiratne A, **Ediriweera DS**, Somaweera R, de Silva HJ, Diggle P, Lalloo DG, Murray KA, Iwamura T. Climate change maladaptation for health: Agricultural practice against shifting seasonal rainfall affects snakebite risk for farmers in the tropics. *iScience*. 2023 Feb 17;26(2).
* Malalasekera AP, Neththikumara N, Somasundaram P, Pathirana S, **Ediriweera C**, **Ediriweera D**, Goonewardena SA, Perera ND, Abeygunasekara A, Jayasekara RW, Wettasinghe K. Clinical Exome Gene Panel Analysis of a Cohort of Urothelial Bladder Cancer Patients from Sri Lanka. *Asian Pacific Journal of Cancer Prevention: APJCP*. 2023;24(5):1533.
* Chandrasinghe P, **Ediriweera EP**, Niriella M, Ranwaka C, Fernando A, Gunawardena H, Kumarage S. North Colombo diverticular disease snap shot audit (VISTA study): a collaborative research initiative. *Sri Lanka Journal of Surgery*. 2023 Mar 31;41(1).
* Mahendra BA, **Ediriweera DS**, Hettiararchchi WG, Hewavisenthi SD. Continuous grading of postgraduate trainees’ performance reflects their success at the end of training formal assessment: a single-centre experience. *Journal of Diagnostic Pathology*. 2023 Dec 31;17(2).
* **Ediriweera DS**, de Silva T, Kasturiratne A, de Silva HJ, Diggle P. Geographically regulated designs of incidence surveys can match the precision of classical survey designs whilst requiring smaller sample sizes: the case of snakebite envenoming in Sri Lanka. *BMJ Global Health*. 2022 Oct 1;7(10):e009500.
* Premawardhena AP, **Ediriweera DS**, Sabouhanian A, Allen A, Rees D, de Silva S, Perera W, Katugaha N, Arambepola M, Yamashita RC, Mettananda S. Survival and complications in patients with haemoglobin E thalassaemia in Sri Lanka: a prospective, longitudinal cohort study. *The Lancet Global Health*. 2022 Jan 1;10(1):e134-41.
* Malalasekera AP, **Ediriweera D**, Goonewardena SA, Perera ND, Abeygunasekara A, Jayasekara RW, Wettasinghe K, Dissanayake VH, Lokuhetty MD. Demographics, pathological characteristics and survival in urothelial bladder cancer in a cohort of Sri Lankan patients. *Ceylon Medical Journal*. 2022; 67: 81-88.
* Padeniya P, **Ediriweera DS**, De Silva A, Niriella M, Premawardhena A. Using FIB-4 score as a screening tool in the assessment of significant liver fibrosis (F2) in patients with transfusion dependent beta thalassaemia: a cross sectional study. *BMJ Open*. 2022;12:e061156.
* Goonathilake P, **Ediriweera D**, Ruban R, Isuru A. Prevalence and correlates of cognitive impairment in schizophrenia: a cross-sectional study from a teaching hospital southern Sri Lanka. *BMC Psychiatry*. 2022. 22, 716.
* Martín G, Erinjery JJ, **Ediriweera D**, de Silva HJ, Lalloo DG, Iwamura T, Murray KA. A mechanistic model of snakebite as a zoonosis: Envenoming incidence is driven by snake ecology, socioeconomics and its impacts on snakes. *PLOS Neglected Tropical Diseases*. 2022. 16(5), e0009867.
* Hettige S, Dasanayaka E, **Ediriweera DS**. Student usage of open educational resources and social media at a Sri Lanka Medical School. *BMC Medical Education*. 2022 Dec;22(1):1-1.
* Malalasekera AP, **Ediriweera D**, Goonewardena S, Perera N, Abeygunasekara A, Jayasekara RW, Wettasinghe TK, Dissanayake VH, Lokuhetty MD. Meta-analysis of global variations in grade of pT1 urothelial bladder cancer and supplementary evaluation of a Sri Lankan cohort. *Sri Lanka Journal of Surgery*. 2022. 40(3),11–9.
* Abayabandara-Herath T, Premaratne I, **Ediriweera D**, Chandrathilake M and Hapangama A. Psychological impact of COVID-19 among a cohort of Sri Lankan medical students: Preliminary results. *Sri Lanka Journal of Psychiatry*. 2022. 13(1), pp.48–50.
* Nisansala R, De Silva S, **Ediriweera D**, Premawardhena A. Morbidity and mortality patterns in patients with thalassaemia during the COVID-19 pandemic in Sri Lanka; A single centre experience. *Asian Journal of Internal Medicine*. 2022;1(1):73–8.
* Jayathunge DN, Silva KG, Thilakaratne S, **Ediriweera D**, Hewavisenthi J. The development of a simple protocol for successful inking of surgical margins with easily accessible colouring agents. *Journal of Diagnostic Pathology*. 2022 Mar 31;16(2).
* Silva KG, Mahendra BA, **Ediriweera D**, Hewavisenthi J. A comparison of expression of ER, PR and p53 immunohistochemical stains between endometrial curetting/biopsy and resected endometrial carcinoma specimens. *Journal of Diagnostic Pathology*. 2022 Mar 31;16(2).
* Jayathunge DN, Silva KG, Thilakaratne S, **Ediriweera D**, Hewavisenthi J. What are the best colours and colour combinations useful in inking surgical margins?. *Journal of Diagnostic Pathology*. 2022 Mar 31;16(2).
* COVIDSurg Collaborative, GlobalSurg Collaborative. SARS-CoV-2 infection and venous thromboembolism after surgery: an international prospective cohort study. *Anaesthesia*. 2022, 77(1), pp. 28-39. 10.1111/anae.15563 [Collaborator entry verified for **Ediriweera D**]
* **Ediriweera DS**, Kasthuriratne A, Pathmeswaran A, Gunawardene NK, Jayamanne SF, Murray K, Iwamura T, Isbister G, Dawson A, Lalloo DG, de Silva HJ. Evaluating spatiotemporal dynamics of snakebite in Sri Lanka: Monthly incidence mapping from a national representative survey sample. *PLOS Neglected Tropical Diseases*. 2021 Jun 1;15(6):e0009447.
* Niriella MA, **Ediriweera DS**, De Silva AP, Premarathna BH, Jayasinghe S, De Silva HJ. Dengue and leptospirosis infection during the coronavirus 2019 outbreak in Sri Lanka. *Transactions of the Royal Society of Tropical Medicine and Hygiene*. 2021 Sep;115(9):944-6.
* Baminiwatta A, Chandradasa M, **Ediriweera D**, Dias S. Factor structure of medical students’ attitudes towards psychiatry: findings from a nationally representative sample from Sri Lanka. *BJPsych Open*. 2021 Jun;7(S1):S124-5.
* Goldstein E, Erinjery JJ, Martin G, Kasturiratne A, **Ediriweera DS**, de Silva HJ, Diggle P, Lalloo DG, Murray KA, Iwamura T. Integrating human behavior and snake ecology with agent-based models to predict snakebite in high risk landscapes. *PLOS Neglected Tropical Diseases*. 2021 Jan 22;15(1):e0009047.
* Martín G, Erinjery J, Gumbs R, Somaweera R, **Ediriweera D**, Diggle PJ, Kasturiratne A, de Silva HJ, Lalloo DG, Iwamura T, Murray KA. Integrating snake distribution, abundance and expert‐derived behavioural traits predicts snakebite risk. *Journal of Applied Ecology*. 2021 Nov 19.
* Finkelstein EA, Krishnan A, Naheed A, Jehan I, de Silva HA, Gandhi M, Lim CW, Chakma N, **Ediriweera DS**, Khan J, Kasturiratne A. Budget impact and cost-effectiveness analyses of the COBRA-BPS multicomponent hypertension management programme in rural communities in Bangladesh, Pakistan, and Sri Lanka. *The Lancet Global Health*. 2021 May 1;9(5):e660-7.
* Pintor AF, Ray N, Longbottom J, Bravo-Vega CA, Yousefi M, Murray KA, **Ediriweera DS**, Diggle PJ. Addressing the global snakebite crisis with geo-spatial analyses–Recent advances and future direction. *Toxicon: X*. 2021 Sep 1;11:100076.
* Niriella MA, **Ediriweera DS**, Kasturiratne A, De Silva ST, Dassanayaka AS, De Silva AP, Kato N, Pathmeswaran A, Wickramasinghe AR, de Silva HJ. Outcomes of NAFLD and MAFLD: results from a community-based, prospective cohort study. *PLOS ONE*. 2021 Feb 3;16(2):e0245762.
* Niriella MA, **Ediriweera DS**, Kasturiratne A, Gunasekara D, De Silva ST, Dassanayaka AS, De Silva AP, Kato N, Pathmeswaran A, Wickramasinghe AR, de Silva HJ. The clinical utility of accurate NAFLD ultrasound grading: Results from a community-based, prospective cohort study. *European Journal of Radiology*. 2021 Mar 1;136:109516.
* Gamakaranage C, Hettiarachchi D, **Ediriweera D**, Jayasinghe S. Symptomatology of Coronavirus Disease 2019 (COVID-19)-Lessons from a meta-analysis across 13 countries. *Asian Journal of Medical Sciences*. 12(11), 3–15.
* Isuru A, Hapangama A, **Ediriweera D**, Samarasinghe L, Fonseka M, Ranawaka U. Prevalence and predictors of new onset depression in the acute phase of stroke. *Asian Journal of Psychiatry*. 2021 May 1;59:102636.
* Baminiwatta A, Chandradasa M, Dias S, **Ediriweera D**. Revisiting the ATP 30: The factor structure of a scale measuring medical students’ attitudes towards psychiatry. *Academic Psychiatry*. 2021 Dec;45(6):716-24.
* Uragoda B, **Ediriweera D**, Paranahewa L, Ekanayake C, Tillakarathna S, Siriwardana R. Presence of fatty liver disease leads to unusual rise of liver enzymes in patients with common bile duct colic. *Annals of Hepato-Biliary-Pancreatic Surgery*. 2021 Jun 30;25(1):S334.
* Gacaferi H, COVIDSurg Collaborative, GlobalSurg Collaborative. Timing of Surgery Following SARS‐CoV‐2 Infection: an International Prospective Cohort Study. *Anaesthesia*. 2021. 76 (6): 748–58. [Collaborator entry verified for **Ediriweera D**]
* COVIDSurg Collaborative, GlobalSurg Collaborative. SARS-CoV-2 vaccination modelling for safe surgery to save lives: data from an international prospective cohort study. *British Journal of Surgery*. 2021. 108(9): 1056-1063. [Collaborator entry verified for **Ediriweera D**]
* COVIDSurg Collaborative, GlobalSurg Collaborative, Nepogodiev D, Simoes JFF, Li E, Picciochi M, Glasbey JC et al. Effects of pre‐operative isolation on postoperative pulmonary complications after elective surgery: an international prospective cohort study. *Anaesthesia*. 2021. 76(11): 1454-1464. [Collaborator entry verified for **Ediriweera D**]
* **Ediriweera DS**, De Silva NR, Malavige GN, De Silva HJ. An epidemiological model to aid decision-making for COVID-19 control in Sri Lanka. *PLOS ONE*. 2020 Aug 27;15(8):e0238340.
* Kasturiratne A, **Ediriweera DS**, De Silva ST, Niriella MA, Thulani UB, Pathmeswaran A, Dassanayake AS, De Silva AP, Chackrewarthy S, Ranawaka U, Kato N. Patterns and predictors of mortality in a semi-urban population-based cohort in Sri Lanka: findings from the Ragama Health Study. *BMJ Open*. 2020 Sep 1;10(9):e038772.
* Isuru A, **Ediriweera D**, Pathmeswaran A, Embuldeniya A, Narammalage H, Warnakulasuriya S, Kuruppuarachchi KA, Hapangama A. Betel-quid use and its effects on symptoms of schizophrenia and extrapyramidal symptoms among a group of patients in a tertiary care hospital in Sri Lanka. *Sri Lanka Journal of Psychiatry*. 2020 Jun 18;11(1).
* De Silva AP, Niriella MA, **Ediriweera DS**, De Alwis JP, Liyanage IK, Ettickan U, Liyanapathirana KV, Undugodage C, de Silva HA, de Silva HJ. Low‐dose melatonin for sleep disturbances in early‐stage cirrhosis: A randomized, placebo‐controlled, cross‐over trial. *JGH Open*. 2020 Aug;4(4):749-56.
* Padeniya P, Siriwardana S, **Ediriweera D**, Samarasinghe N, Silva S, Silva I, Ahamed N, Niriella M, Premawardhena A. Comparison of liver MRI R2 (FerriScan®) VS liver MRI T2* as a measure of body iron load in a cohort of beta thalassaemia major patients. *Orphanet Journal of Rare Diseases*. 2020 Jan 22;15(1):26.
* Hettige S, Dasanayaka E, **Ediriweera DS**. Usage of cloud storage facilities by medical students in a low-middle income country, Sri Lanka: a cross sectional study. *BMC Medical Informatics and Decision Making*. 2020 Jan 28;20(1):10.
* Siriwardana RC, Sivasundaram T, Paranaheva L, **Ediriweera DS**. Computed tomography–based evaluation of segmental variation of liver density and its implications. *Indian Journal of Gastroenterology*. 2020 Feb;39(1):60-5.
* Warnakulasuriya T, Williams S, Weerakkody T, Dabarera M, Rodrigo K, Waduge VA, **Ediriweera D**, Siriwardena N, Wickremasinghe R. Background radiation levels near a mineral sand mining factory in Sri Lanka: correlation of radiation measurements with micronuclei frequency. *Radiation Protection Dosimetry*. 2020 Mar;189(1):114-26.
* Niriella MA, **Ediriweera DS**, De Silva AP, Premarathna R, Balasooriya P, Duminda KD, Malavige NG, Wanigasuriya K, Lekamwasam S, Kularathne SA, Siribaddana S. Hydroxychloroquine for Post-Exposure Prophylaxis of COVID-19 among naval personnel: study protocol for a randomized controlled trial. *Trials*. 2020 Aug 27;21(1):748.
* Premawardhena AP, De Silva ST, Goonatilleke MD, **Ediriweera DS**, Mettananda S, Rodrigo BR, Allen A, Weatherall DJ. Marriage patterns in Sri Lanka and the prevalence of parental consanguinity in patients with β-thalassaemia: a cross-sectional descriptive analysis. *Journal of Biosocial Science*. 2020 Jul;52(4):573-84.
* Jafar TH, Gandhi M, De Silva HA, Jehan I, Naheed A, Finkelstein EA, Turner EL, Morisky D, Kasturiratne A, Khan AH, Clemens JD, COBRA-BPS Study Group*. A community-based intervention for managing hypertension in rural South Asia. *New England Journal of Medicine*. 2020 Feb 20;382(8):717-26. [Collaborator entry verified for **Ediriweera DS**]
* **Ediriweera DS**, Gunawardena S, Gunawardena NK, Iddawela D, Kannathasan S, Murugananthan A, Yahathugoda C, Pathmeswaran A, Diggle PJ, de Silva N. Reassessment of the prevalence of soil-transmitted helminth infections in Sri Lanka to enable a more focused control programme: a cross-sectional national school survey with spatial modelling. *The Lancet Global Health*. 2019 Sep 1;7(9):e1237-46.
* **Ediriweera DS**, Kasthuriratne A, Pathmeswaran A, Gunawardene NK, Jayamanne SF, Murray K, Iwamura T, Lalloo DG, de Silva HJ, Diggle PJ. Adjusting for spatial variation when assessing individual-level risk: A case-study in the epidemiology of snake-bite in Sri Lanka. *PLOS ONE*. 2019 Oct 3;14(10):e0223021.
* De Silva ST, Niriella MA, **Ediriweera DS**, Kottahachchi D, Kasturiratne A, de Silva AP, Dassanayaka AS, Pathmeswaran A, Wickramasinghe R, Kato N, de Silva HJ. Incidence and risk factors for metabolic syndrome among urban, adult Sri Lankans: a prospective, 7-year community cohort, follow-up study. *Diabetology & Metabolic Syndrome*. 2019 Aug 14;11(1):66.
* Perera M, de Silva CK, Tavajoh S, Kasturiratne A, Luke NV, **Ediriweera DS**, Ranasinha CD, Legido-Quigley H, de Silva HA, Jafar TH. Patient perspectives on hypertension management in health system of Sri Lanka: a qualitative study. *BMJ Open*. 2019 Oct 1;9(10):e031773.
* Perera K, Kodisinghe SK, **Ediriweera DS**, Moratuwagama D, Williams S, Pathmeswaran A, Niriella MA, de Silva HJ. Percentage of small platelets on peripheral blood smear and Child-Turcott-Pugh class can predict the presence of oesophageal varices in newly diagnosed patients with cirrhosis: development of a prediction model for resource-limited settings. *BMC Gastroenterology*. 2019 Jul 26;19(1):134.
* Niriella MA, Kasturiratna A, Beddage T, **Ediriweera DS**, De Silva ST, Perera KR, Subasinghe CE, Kodisinghe SK, Piyaratna TC, Rishikesawan V, Dassanayaka AS. Non-resolution of non-alcoholic fatty liver disease (NAFLD) among urban, adult Sri Lankans in the general population: A prospective, cohort follow-up study. *PLOS ONE*. 2019 Oct 29;14(10):e0224474.
* Ratnayake RM, Epitakaduwa C, Jayatunge DN, **Ediriweera D**, Hewavisenthi SD. Comparison of Mucin Patterns in Colonic Pathologies by Histochemistry. *Journal of Diagnostic Pathology*. 2019 Dec 30;14(2).
* Somasundaram N, Ranathunga I, Gunawardana K, Ahamed M, **Ediriweera D**, Antonypillai CN, Kalupahana N. High prevalence of overweight/obesity in urban Sri Lanka: findings from the Colombo urban study. *Journal of Diabetes Research*. 2019;2019(1):2046428.
* Subasinghe CJ, Gunawardane K, **Ediriweera D**, Somasundaram NP. Prevalence of vitamin D deficiency/insufficiency and its metabolic associations in an urban setting in Sri Lanka: data from Colombo urban study. *Sri Lanka Journal of Diabetes Endocrinology and Metabolism*. 2019 Dec 12;9(2).
* Somasundaram NP, Ranathunga I, Gunawardana K, **Ediriweera DS**. High prevalence of diabetes mellitus in Sri Lankan urban population–data from Colombo urban study. *Sri Lanka Journal of Diabetes Endocrinology and Metabolism*. 2019 Dec 12;9(2):8.
* **Ediriweera DS**, Diggle PJ, Kasturiratne A, Pathmeswaran A, Gunawardena NK, Jayamanne SF, Isbister GK, Dawson A, Lalloo DG, de Silva HJ. Evaluating temporal patterns of snakebite in Sri Lanka: the potential for higher snakebite burdens with climate change. *International Journal of Epidemiology*. 2018 Dec 1;47(6):2049-58.
* **Ediriweera DS**, Karunapema P, Pathmeswaran A, Arnold M. Increase in premature mortality due to non-communicable diseases in Sri Lanka during the first decade of the twenty-first century. *BMC Public Health*. 2018 Dec;18(1):1-6.
* **Ediriweera DS**, Dilina N, Saparamadu V, Fernando I, Kurukulasuriya B, Fernando D. Aspirin is associated with low oral pH levels and antacid helps to increase oral pH. *BMC Research Notes*. 2018 Dec;11(1):1-5.
* Malalasekera AP, Sivasuganthan K, Sarangan S, Thaneshan K, Weerakoon DN, Mathangasinghe Y, Gunasekera CL, Mallawaarachchi S, Nanayakkara ND, Anthony DJ, **Ediriweera D**. Morphological variations of the human ejaculatory ducts in relation to the prostatic urethra. *Clinical Anatomy*. 2018 May;31(4):456-61.
* Karuppiah D, Cooray MSA, Nomasundaram N, and **Ediriweera DS**. Screening of Cushing's syndrome in patients with poorly controlled type 2 diabetes with hypertension and obesity. *International Journal of Advanced Research*. 2018 Jan; 6 (1): 603-610.
* **Ediriweera DS**, Kasturiratne A, Pathmeswaran A, Gunawardena NK, Jayamanne SF, Lalloo DG, de Silva HJ. Health seeking behavior following snakebites in Sri Lanka: Results of an island wide community based survey. *PLOS Neglected Tropical Diseases*. 2017 Nov 6;11(11):e0006073.
* **Ediriweera DS**, Dilina N, Perera U, Flores F, Samita SJ. Risk of low birth weight on adulthood hypertension-evidence from a tertiary care hospital in a South Asian country, Sri Lanka: a retrospective cohort study. *BMC Public Health*. 2017 Apr 24;17(1):358.
* Chandrasinghe PC, **Ediriweera DS**, Nazar T, Kumarage S, Hewavisenthi J, Deen KI. Overall survival of elderly patients having surgery for colorectal cancer is comparable to younger patients: results from a South Asian population. *Gastroenterology Research and Practice*. 2017;2017(1):9670512.
* Chandrasinghe PC, **Ediriweera DS**, Hewavisenthi J, Kumarage SK, Fernando FR, Deen KI. Colorectal cancer burden and trends in a South Asian cohort: experience from a regional tertiary care center in Sri Lanka. *BMC Research Notes*. 2017 Oct 30;10(1):535.
* Isuru A, Rodrigo A, Wijesinghe C, **Ediriweera D**, Premadasa S, Wijesekara C, Kuruppuarachchi L. A randomized, double-blind, placebo-controlled trial on the role of preemptive analgesia with acetaminophen [paracetamol] in reducing headache following electroconvulsive therapy [ECT]. *BMC Psychiatry*. 2017 Dec;17(1):1-7.
* Wijesooriya WR, Herath YB, Sugandhi RA, Weerawardhana A, **Ediriweera DS**. Antibiotic sensitivity pattern for non-beta lactam antibiotics and carbapenems in extended-spectrum beta-lactamase (ESBL) producing uropathogens versus non-ESBL producing uropathogens. *Sri Lankan Journal of Infectious Diseases*. 2017, 7(2), pp.92–99.
* Siriwardana RC, Niriella MA, Dassanayake A, **Ediriweera D**, Gunetilleke B, Sivasundaram T, de Silva J. Association of Serum Ferritin with Diabetes and Alcohol in Patients with Non-Viral Liver Disease-Related Hepatocellular Carcinoma. *Liver Cancer*. 2017;6(4):307-12.
* **Ediriweera DS**, Kasturiratne A, Pathmeswaran A, Gunawardena NK, Wijayawickrama BA, Jayamanne SF, Isbister GK, Dawson A, Giorgi E, Diggle PJ, Lalloo DG, de Silva HJ. Mapping the risk of snakebite in Sri Lanka-a national survey with geospatial analysis. *PLOS Neglected Tropical Diseases*. 2016 Jul 8;10(7):e0004813.
* **Ediriweera DS**, Kumarage S, Deen KI. Comparison of hazard of death following surgery for colon versus rectal cancer. *Ceylon Medical Journal*. 2016 Jun 23;61(2).
* Adhihetty D, Kitulwatte NC, Hathagoda KL, Weeraratne CT, de Silva S, **Ediriweera EP**. Outcome of children transported for pediatric intensive care to a tertiary care setting in Sri Lanka. *Sri Lanka Journal of Child Health*. 2016 Jun 6;45(2).
* Sigera S, Perera J, Rasarathinam J, Samaranayake D, **Ediriweera D**. Seroprevalence of Bordetella pertussis specific Immunoglobulin G antibody levels among asymptomatic individuals aged 4 to 24 years: a descriptive cross sectional study from Sri Lanka. *BMC Infectious Diseases*. 2016 Dec;16(1):1-9.
* Bandara KD, Thilakarathna GH, Modaragama SD, Jayawardana MA, Rathnayake HA, **Ediriweera D**. Profile of automobile related accidents encountered at District General Hospital Gampaha. *Anuradhapura Medical Journal*. 2015 Oct 28;9(2Supp).
* Chandrasinghe PC, **Ediriweera DS**, Hewavisenthi J, Kumarage S, Deen KI. The total number of lymph nodes harvested is associated with better survival in stages II and III colorectal cancer. *Indian Journal of Gastroenterology*. 2014 May;33(3):249-53.
* Kahandawa S, Somasundaram NP, **Ediriweera DS**, Kusumsiri DP, Ellawala S, Chandrika GH, Ransarini KG. Prevalence of thyroid dysfunction among type 2 diabetic patients attending the Diabetes Clinic, National Hospital of Sri Lanka. *Sri Lanka Journal of Diabetes Endocrinology and Metabolism*. 2014 Aug 5;4(1).
* Chandrasinghe PC, **Ediriweera DS**, Kumarage SK, Deen KI. Pre-operative hypoalbuminaemia predicts poor overall survival in rectal cancer: a retrospective cohort analysis. *BMC Clinical Pathology*. 2013 Apr 16;13(1):12.
* **Ediriweera EP**, Ranatunga PE, **Jayamanne BD**. Mobile software prototype-Patient guidance for laboratory investigation preparations. *Sri Lanka Journal of Bio-Medical Informatics*. 2011 Oct 28;1.



